name: CI

on: [ push, pull_request ]

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files in the repository
        uses: actions/checkout@v3

      - name: Compile cpp-assert
        run: make

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files in the repository
        uses: actions/checkout@v3

      - name: Compile and run tests
        run: make clean && make && ./main && ./main self-test && ./main test
